#!/bin/bash
SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
osascript $SCRIPTDIR/hideAllWindows.scpt; 
osascript $SCRIPTDIR/minimizeSafari.scpt;
sleep 2;
open -a Terminal $SCRIPTDIR/prioritize; 
